/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/d/workspace/dds-dist/share/CycloneDDS/examples/helloworld/HelloWorldData.h
  Source: /mnt/d/workspace/dds-dist/share/CycloneDDS/examples/helloworld/HelloWorldData.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC__MNT_D_WORKSPACE_DDS_DIST_SHARE_CYCLONEDDS_EXAMPLES_HELLOWORLD_HELLOWORLDDATA_H
#define DDSC__MNT_D_WORKSPACE_DDS_DIST_SHARE_CYCLONEDDS_EXAMPLES_HELLOWORLD_HELLOWORLDDATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct HelloWorldData_Msg
{
  int32_t userID;
  char * message;
} HelloWorldData_Msg;

extern const dds_topic_descriptor_t HelloWorldData_Msg_desc;

#define HelloWorldData_Msg__alloc() \
((HelloWorldData_Msg*) dds_alloc (sizeof (HelloWorldData_Msg)));

#define HelloWorldData_Msg_free(d,o) \
dds_sample_free ((d), &HelloWorldData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_D_WORKSPACE_DDS_DIST_SHARE_CYCLONEDDS_EXAMPLES_HELLOWORLD_HELLOWORLDDATA_H */
